[package]
name = "peace_item_sh_sync_cmd"
description = "Manages a synchronization shell command for the peace framework"
documentation = "https://docs.rs/peace_item_sh_sync_cmd/"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = true
test = false

[dependencies]
chrono = { workspace = true, default-features = false }
miette = { workspace = true, optional = true }
peace = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["net", "time", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }

[features]
default = []
error_reporting = ["peace/error_reporting"]
output_progress = ["peace/output_progress"]
