[package]
name = "peace_resources"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.2"
edition = "2021"
description = "Runtime resources for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_resources/"
readme = "../../README.md"
categories = ["configuration"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
peace_core = { version = "0.0.2", path = "../core" }
peace_data = { version = "0.0.2", path = "../data" }
resman = { version = "0.15.0", features = ["debug"] }
serde = { version = "1.0.145", features = ["derive"] }
tokio = { version = "1.21.1", features = ["sync"] }
type_reg = { version = "0.3.1", features = ["debug", "untagged", "ordered"] }
